/**
 * Localised city names, keyed by ISO 3166-1 alpha-2 then by the *exact* English
 * spelling the city API returns.
 *
 * Cities are fetched per country from CountriesNow, which serves English only —
 * so unlike countries, there is nothing to switch to when the language changes.
 * No keyless localised city API exists to fill the gap: Wikidata's SPARQL
 * endpoint has the labels but answers in 7-11s (and timed out outright at 60s
 * once while this was being built), and matching its entries back onto the API's
 * spellings only reached 29% — while confidently mismatching Agadir onto Agadir
 * Bouachiba, a different town. Slow, partial and occasionally wrong is worse than
 * untranslated, so the mapping is resolved here, once, instead of at runtime.
 *
 * Entries come from Wikidata where its English label matched the API's exactly
 * (no alias matching — that is what produced the Agadir error), filled in by hand
 * for the well-known cities it missed. Anything not confidently known was left
 * out rather than guessed: a city with no entry falls back to the Latin spelling
 * the API gave, which is always readable, whereas a wrong Arabic name is not
 * something the user can recover from.
 *
 * Only Morocco is mapped — it is where the event is and where essentially every
 * registration comes from. Adding a country is purely additive: drop in its ISO2
 * key and `cityLabel()` starts using it, no code change.
 *
 * The key is the canonical value: it is what gets submitted as `ville`, so the
 * back office keeps one spelling per city whichever language was used to sign up
 * — the same rule `pays` follows by always being stored in French.
 */
export const CITY_NAMES = {
  MA: {
    "Afourer": { fr: "Afourer", ar: "أفورار" },
    "Agadir": { fr: "Agadir", ar: "أكادير" },
    "Agadir Melloul": { fr: "Agadir Melloul", ar: "أكادير ملول" },
    "Agadir-Ida-ou-Tnan": { fr: "Agadir-Ida-Outanane", ar: "أكادير إدا وتنان" },
    "Agdz": { fr: "Agdz", ar: "أكدز" },
    "Aguelmous": { fr: "Aguelmous", ar: "أكلموس" },
    "Ahfir": { fr: "Ahfir", ar: "أحفير" },
    "Aïn Beni Mathar": { fr: "Aïn Beni Mathar", ar: "عين بني مطهر" },
    "Aïn Leuh": { fr: "Aïn Leuh", ar: "عين اللوح" },
    "Ait Melloul": { fr: "Aït Melloul", ar: "أيت ملول" },
    "Akhfennir": { fr: "Akhfennir", ar: "أخفنير" },
    "Aknoul": { fr: "Aknoul", ar: "أكنول" },
    "Al Aaroui": { fr: "Al Aaroui", ar: "العروي" },
    "Al Fqih Ben Çalah": { fr: "Fquih Ben Salah", ar: "الفقيه بن صالح" },
    "Al Hoceima": { fr: "Al Hoceïma", ar: "الحسيمة" },
    "Al Hoceïma": { fr: "Al Hoceïma", ar: "الحسيمة" },
    "Al-Haouz": { fr: "Al Haouz", ar: "الحوز" },
    "Al-Hoceima": { fr: "Al Hoceïma", ar: "الحسيمة" },
    "Alnif": { fr: "Alnif", ar: "النيف" },
    "Aoufous": { fr: "Aoufous", ar: "أوفوس" },
    "Aoulouz": { fr: "Aoulouz", ar: "أولوز" },
    "Aourir": { fr: "Aourir", ar: "أورير" },
    "Aousserd": { fr: "Aousserd", ar: "أوسرد" },
    "Arbaoua": { fr: "Arbaoua", ar: "عرباوة" },
    "Arfoud": { fr: "Arfoud", ar: "أرفود" },
    "Asilah": { fr: "Assilah", ar: "أصيلة" },
    "Assa": { fr: "Assa", ar: "آسا" },
    "Assa-Zag": { fr: "Assa-Zag", ar: "آسا الزاك" },
    "Azemmour": { fr: "Azemmour", ar: "أزمور" },
    "Azilal": { fr: "Azilal", ar: "أزيلال" },
    "Azilal Province": { fr: "Province d'Azilal", ar: "إقليم أزيلال" },
    "Azrou": { fr: "Azrou", ar: "أزرو" },
    "Benguerir": { fr: "Benguerir", ar: "بن جرير" },
    "Beni Mellal": { fr: "Béni Mellal", ar: "بني ملال" },
    "Beni-Mellal": { fr: "Béni Mellal", ar: "بني ملال" },
    "Benslimane": { fr: "Benslimane", ar: "بن سليمان" },
    "Berkane": { fr: "Berkane", ar: "بركان" },
    "Berrechid": { fr: "Berrechid", ar: "برشيد" },
    "Berrechid Province": { fr: "Province de Berrechid", ar: "إقليم برشيد" },
    "Bhalil": { fr: "Bhalil", ar: "بهاليل" },
    "Bni Bouayach": { fr: "Bni Bouayach", ar: "بني بوعياش" },
    "Bouarfa": { fr: "Bouarfa", ar: "بوعرفة" },
    "Boujdour": { fr: "Boujdour", ar: "بوجدور" },
    "Boujniba": { fr: "Boujniba", ar: "بوجنيبة" },
    "Boulaouane": { fr: "Boulaouane", ar: "بولعوان" },
    "Boulemane": { fr: "Boulemane", ar: "بولمان" },
    "Bouskoura": { fr: "Bouskoura", ar: "بوسكورة" },
    "Bouznika": { fr: "Bouznika", ar: "بوزنيقة" },
    "Brikcha": { fr: "Brikcha", ar: "بريكشة" },
    "Bzou": { fr: "Bzou", ar: "بزو" },
    "Casablanca": { fr: "Casablanca", ar: "الدار البيضاء" },
    "Chefchaouen Province": { fr: "Province de Chefchaouen", ar: "إقليم شفشاون" },
    "Chefchaouene": { fr: "Chefchaouen", ar: "شفشاون" },
    "Chichaoua": { fr: "Chichaoua", ar: "شيشاوة" },
    "Chtouka-Ait-Baha": { fr: "Chtouka-Aït Baha", ar: "شتوكة آيت باها" },
    "Dar Ould Zidouh": { fr: "Dar Ould Zidouh", ar: "دار ولد زيدوح" },
    "Debdou": { fr: "Debdou", ar: "دبدو" },
    "Demnate": { fr: "Demnate", ar: "دمنات" },
    "Deroua": { fr: "Deroua", ar: "الدروة" },
    "Driouch Province": { fr: "Province de Driouch", ar: "إقليم الدريوش" },
    "El Aïoun": { fr: "El Aïoun Sidi Mellouk", ar: "العيون سيدي ملوك" },
    "El Gara": { fr: "El Gara", ar: "الكارة" },
    "El Hajeb": { fr: "El Hajeb", ar: "الحاجب" },
    "El Jadid": { fr: "El Jadida", ar: "الجديدة" },
    "El Jadida": { fr: "El Jadida", ar: "الجديدة" },
    "El Ksiba": { fr: "El Ksiba", ar: "القصيبة" },
    "El-Hajeb": { fr: "El-Hajeb", ar: "الحاجب" },
    "El-Jadida": { fr: "El Jadida", ar: "الجديدة" },
    "Erfoud": { fr: "Erfoud", ar: "أرفود" },
    "Errachidia": { fr: "Errachidia", ar: "الرشيدية" },
    "Es-Semara": { fr: "Es-Semara", ar: "السمارة" },
    "Essaouira": { fr: "Essaouira", ar: "الصويرة" },
    "Fahs-Anjra": { fr: "Fahs-Anjra", ar: "الفحص أنجرة" },
    "Fes": { fr: "Fès", ar: "فاس" },
    "Fès": { fr: "Fès", ar: "فاس" },
    "Fès al Bali": { fr: "Fès el-Bali", ar: "فاس البالي" },
    "Figuig": { fr: "Figuig", ar: "فجيج" },
    "Fkih Ben Salah": { fr: "Fquih Ben Salah", ar: "الفقيه بن صالح" },
    "Fnidek": { fr: "Fnideq", ar: "الفنيدق" },
    "Fquih Ben Salah Province": { fr: "Province de Fquih Ben Salah", ar: "إقليم الفقيه بن صالح" },
    "Guelmim": { fr: "Guelmim", ar: "كلميم" },
    "Gueltat Zemmour": { fr: "Gueltat Zemmour", ar: "كلتة زمور" },
    "Guercif": { fr: "Guercif", ar: "جرسيف" },
    "Guercif Province": { fr: "Province de Guercif", ar: "إقليم جرسيف" },
    "Had Kourt": { fr: "Had Kourt", ar: "حد كورت" },
    "Ifrane": { fr: "Ifrane", ar: "إفران" },
    "Imilchil": { fr: "Imilchil", ar: "إميلشيل" },
    "Imzouren": { fr: "Imzouren", ar: "إمزورن" },
    "Inezgane": { fr: "Inezgane", ar: "إنزكان" },
    "Inezgane-Ait Melloul": { fr: "Inezgane-Aït Melloul", ar: "إنزكان أيت ملول" },
    "Itzer": { fr: "Itzer", ar: "إيتزر" },
    "Jerada": { fr: "Jerada", ar: "جرادة" },
    "Jorf": { fr: "Jorf", ar: "جرف" },
    "Kasba Tadla": { fr: "Kasba Tadla", ar: "قصبة تادلة" },
    "Kelaa-Des-Sraghna": { fr: "El Kelâa des Sraghna", ar: "قلعة السراغنة" },
    "Kelaat Mgouna": { fr: "Kelâat M'Gouna", ar: "قلعة مكونة" },
    "Kenitra": { fr: "Kénitra", ar: "القنيطرة" },
    "Kenitra Province": { fr: "Province de Kénitra", ar: "إقليم القنيطرة" },
    "Kerrouchen": { fr: "Kerrouchen", ar: "كروشن" },
    "Khemisset": { fr: "Khémisset", ar: "الخميسات" },
    "Khenifra": { fr: "Khénifra", ar: "خنيفرة" },
    "Khouribga": { fr: "Khouribga", ar: "خريبكة" },
    "Khouribga Province": { fr: "Province de Khouribga", ar: "إقليم خريبكة" },
    "Ksar el Kebir": { fr: "Ksar el-Kebir", ar: "القصر الكبير" },
    "Ksar El Kebir": { fr: "Ksar el-Kebir", ar: "القصر الكبير" },
    "Laayoune": { fr: "Laâyoune", ar: "العيون" },
    "Larache": { fr: "Larache", ar: "العرائش" },
    "M'Diq-Fnideq": { fr: "M'Diq-Fnideq", ar: "المضيق الفنيدق" },
    "Marrakech": { fr: "Marrakech", ar: "مراكش" },
    "Marrakesh": { fr: "Marrakech", ar: "مراكش" },
    "Martil": { fr: "Martil", ar: "مرتيل" },
    "Mechraa Bel Ksiri": { fr: "Mechra Bel Ksiri", ar: "مشرع بلقصيري" },
    "Mediouna": { fr: "Mediouna", ar: "مديونة" },
    "Mehediyah": { fr: "Mehdia", ar: "المهدية" },
    "Meknes": { fr: "Meknès", ar: "مكناس" },
    "Meknès": { fr: "Meknès", ar: "مكناس" },
    "Mhamid": { fr: "M'Hamid", ar: "امحاميد" },
    "Midar": { fr: "Midar", ar: "ميضار" },
    "Midelt": { fr: "Midelt", ar: "ميدلت" },
    "Missour": { fr: "Missour", ar: "ميسور" },
    "Mohammedia": { fr: "Mohammédia", ar: "المحمدية" },
    "Moulay Bouchta": { fr: "Moulay Bouchta", ar: "مولاي بوشتى" },
    "Moulay-Yacoub": { fr: "Moulay Yacoub", ar: "مولاي يعقوب" },
    "Nador": { fr: "Nador", ar: "الناظور" },
    "Nouaceur": { fr: "Nouaceur", ar: "النواصر" },
    "Oualidia": { fr: "Oualidia", ar: "الوليدية" },
    "Ouarzazat": { fr: "Ouarzazate", ar: "ورزازات" },
    "Ouarzazate": { fr: "Ouarzazate", ar: "ورزازات" },
    "Ouazzane": { fr: "Ouezzane", ar: "وزان" },
    "Oued Amlil": { fr: "Oued Amlil", ar: "واد أمليل" },
    "Oued Laou": { fr: "Oued Laou", ar: "وادي لو" },
    "Oued Zem": { fr: "Oued Zem", ar: "وادي زم" },
    "Oued-Ed-Dahab": { fr: "Oued Ed-Dahab", ar: "وادي الذهب" },
    "Ouezzane": { fr: "Ouezzane", ar: "وزان" },
    "Ouezzane Province": { fr: "Province d'Ouezzane", ar: "إقليم وزان" },
    "Oujda": { fr: "Oujda", ar: "وجدة" },
    "Oujda-Angad": { fr: "Oujda-Angad", ar: "وجدة أنكاد" },
    "Oukaïmedene": { fr: "Oukaïmeden", ar: "أوكايمدن" },
    "Oulad Frej": { fr: "Oulad Frej", ar: "أولاد فرج" },
    "Oulad Tayeb": { fr: "Oulad Tayeb", ar: "أولاد الطيب" },
    "Oulad Teima": { fr: "Oulad Teïma", ar: "أولاد تايمة" },
    "Oulad Teïma": { fr: "Oulad Teïma", ar: "أولاد تايمة" },
    "Oulmes": { fr: "Oulmès", ar: "ولماس" },
    "Rabat": { fr: "Rabat", ar: "الرباط" },
    "Reçani": { fr: "Rissani", ar: "الريصاني" },
    "Rehamna": { fr: "Rehamna", ar: "الرحامنة" },
    "Safi": { fr: "Safi", ar: "آسفي" },
    "Saidia": { fr: "Saïdia", ar: "السعيدية" },
    "Sale": { fr: "Salé", ar: "سلا" },
    "Sefrou": { fr: "Séfrou", ar: "صفرو" },
    "Selouane": { fr: "Selouane", ar: "سلوان" },
    "Settat": { fr: "Settat", ar: "سطات" },
    "Settat Province": { fr: "Province de Settat", ar: "إقليم سطات" },
    "Setti Fatma": { fr: "Setti Fatma", ar: "ستي فاطمة" },
    "Sidi Bennour": { fr: "Sidi Bennour", ar: "سيدي بنور" },
    "Sidi Bousber": { fr: "Sidi Bousber", ar: "سيدي بوسبر" },
    "Sidi Ifni": { fr: "Sidi Ifni", ar: "سيدي إفني" },
    "Sidi Qacem": { fr: "Sidi Kacem", ar: "سيدي قاسم" },
    "Sidi Rahhal": { fr: "Sidi Rahhal", ar: "سيدي رحال" },
    "Sidi Redouane": { fr: "Sidi Redouane", ar: "سيدي رضوان" },
    "Sidi Slimane": { fr: "Sidi Slimane", ar: "سيدي سليمان" },
    "Sidi Smai’il": { fr: "Sidi Smaïl", ar: "سيدي إسماعيل" },
    "Sidi Yahia El Gharb": { fr: "Sidi Yahya El Gharb", ar: "سيدي يحيى الغرب" },
    "Sidi-Kacem": { fr: "Sidi Kacem", ar: "سيدي قاسم" },
    "Skhirat": { fr: "Skhirate", ar: "الصخيرات" },
    "Skhirate": { fr: "Skhirate", ar: "الصخيرات" },
    "Skhirate-Temara": { fr: "Skhirate-Témara", ar: "الصخيرات تمارة" },
    "Smara": { fr: "Es-Semara", ar: "السمارة" },
    "Smimou": { fr: "Smimou", ar: "سميمو" },
    "Souq Larb’a al Gharb": { fr: "Souk El Arbaa", ar: "سوق أربعاء الغرب" },
    "Tafraout": { fr: "Tafraout", ar: "تافراوت" },
    "Taghazout": { fr: "Taghazout", ar: "تغازوت" },
    "Tahala": { fr: "Tahla", ar: "تاهلة" },
    "Tahla": { fr: "Tahla", ar: "تاهلة" },
    "Taliouine": { fr: "Taliouine", ar: "تالوين" },
    "Tamanar": { fr: "Tamanar", ar: "تمنار" },
    "Tamri": { fr: "Tamri", ar: "تمري" },
    "Tan-Tan": { fr: "Tan-Tan", ar: "طانطان" },
    "Tanger-Assilah": { fr: "Tanger-Assilah", ar: "طنجة أصيلة" },
    "Tangier": { fr: "Tanger", ar: "طنجة" },
    "Taounate": { fr: "Taounate", ar: "تاونات" },
    "Taourirt": { fr: "Taourirt", ar: "تاوريرت" },
    "Tarfaya": { fr: "Tarfaya", ar: "طرفاية" },
    "Targuist": { fr: "Targuist", ar: "تارجيست" },
    "Taroudannt": { fr: "Taroudant", ar: "تارودانت" },
    "Taroudant": { fr: "Taroudant", ar: "تارودانت" },
    "Tata": { fr: "Tata", ar: "طاطا" },
    "Taza": { fr: "Taza", ar: "تازة" },
    "Taznakht": { fr: "Taznakht", ar: "تازناخت" },
    "Telouet": { fr: "Telouet", ar: "تلوات" },
    "Temara": { fr: "Témara", ar: "تمارة" },
    "Tetouan": { fr: "Tétouan", ar: "تطوان" },
    "Tétouan": { fr: "Tétouan", ar: "تطوان" },
    "Tiflet": { fr: "Tiflet", ar: "تيفلت" },
    "Tinghir": { fr: "Tinghir", ar: "تنغير" },
    "Tinghir Province": { fr: "Province de Tinghir", ar: "إقليم تنغير" },
    "Tit Mellil": { fr: "Tit Mellil", ar: "تيط مليل" },
    "Tiznit": { fr: "Tiznit", ar: "تيزنيت" },
    "Tiztoutine": { fr: "Tiztoutine", ar: "تزطوطين" },
    "Touissite": { fr: "Touissite", ar: "توسيت" },
    "Youssoufia": { fr: "Youssoufia", ar: "اليوسفية" },
    "Zagora": { fr: "Zagora", ar: "زاكورة" },
    "Zaïo": { fr: "Zaïo", ar: "زايو" },
    "Zawyat an Nwaçer": { fr: "Zaouiat Ennouaceur", ar: "زاوية النواصر" },
    "Zawyat ech Cheïkh": { fr: "Zaouiat Cheikh", ar: "زاوية الشيخ" },
    "Zoumi": { fr: "Zoumi", ar: "زومي" },
  },
};
